package:
  name: qimage2ndarray
  version: 1.4

source:
  fn: qimage2ndarray-master.zip
  url: https://github.com/hmeine/qimage2ndarray/archive/master.zip
  # sha1: 1c1e3f8ccb46c806247f4341b67c196fc73b6546
  
build:                   
  number: 2    

requirements:
  build:
    - python
    - pyside
    - numpy
	
  run:
    - python
    - pyside
    - numpy


about:
  home: https://bitbucket.org/groakat/ffvideo/
  license: Standard PIL license
