package:
  name: pluginmanager
  version: 0.0.1

source:
  fn: master.zip
  url: https://github.com/groakat/pluginManager/archive/master.zip
  sha1: 00c46ebafcf0fe447906e9370a94f2594497cc2b
  
build:                   
  number: 1             

requirements:
  build:
    - python
    - setuptools
    - numpy
	
  run:
    - python


about:
  home: https://github.com/groakat/pluginManager
  license: ---
