package:
  name: videotagger-dependencies
  version: 0.0.1
  
  
  
build:                   
  number: 10

requirements:
	
  run:
    - ffvideo
    - qimage2ndarray
    - numpy
    - ipython
    - colorama
    - pyzmq
    - scipy
    - pil
    - zerorpc
    - matplotlib
    - setuptools
    - pluginmanager
    - cython             [win]
    - mingw				 [win]
    - pywin32           [win]
    - libpython         [win]
    


about:
  home: https://bitbucket.org/groakat/ffvideo/
  license: Standard PIL license
