package:
  name: videotagger-dependencies
  version: 0.0.1
  
  
  
build:                   
  number: 7

requirements:
	
  run:
    - ffvideo
    - qimage2ndarray
    - numpy
    - ipython
    - colorama
    - pyzmq
    - scipy
    - pil
    - zerorpc


about:
  home: https://bitbucket.org/groakat/ffvideo/
  license: Standard PIL license
