package:
  name: pox
  version: 0.2.2

source:
  fn: pox-0.2.2.zip
  url: https://pypi.python.org/packages/source/p/pox/pox-0.2.2.zip
  
build:                   
  number: 2          

requirements:
  build:
    - python
	
  run:
    - python


about:
  home: https://github.com/noxrepo/pox
  license: Apache 2.0
