package:
  name: ffvideo
  version: 0.0.14

source:
  fn: default.zip
  url: https://bitbucket.org/groakat/ffvideo/get/default.zip
#  md5: cf42c695fab68116af2c8ef816fca0d9
  
build:                   
  number: 6              

requirements:
  build:
    - python
    - cython             [win]
    - mingw				 [win]
    - ffmpeg-dev         	
    - cython
    - python
    - pywin32           [win]
    - setuptools
    - libpython         [win]
	
  run:
    - python
    - ffmpeg-shared         
#    - cython
#    - mingw
#    - pywin32
#    - setuptools
#    - libpython


about:
  home: https://bitbucket.org/groakat/ffvideo/
  license: Standard PIL license
