package:
  name: ffvideo
  version: 0.0.17

source:
  fn: master.zip
  url: https://github.com/groakat/ffvideo/archive/master.zip
  sha256: faaf710d27610232d8765f504ad99516d6da00a3471a85b11a841cd1626ce025
#  md5: cf42c695fab68116af2c8ef816fca0d9
  
build:                   
  number: 1          

requirements:
  build:
    - python
    - cython             [win]
    - mingw				 [win]
    - ffmpeg-shared         	
    - ffmpeg-dev                  	
    - cython
    - python
    - numpy
    - pywin32           [win]
    - setuptools
    - libpython         [win]
	
  run:
    - python
    - numpy
    - ffmpeg-shared  
    - ffmpeg-dev       
#    - cython
#    - mingw
#    - pywin32
#    - setuptools
#    - libpython


about:
  home: https://bitbucket.org/groakat/ffvideo/
  license: Standard PIL license
