package:
  name: libogg
  version: 1.3.2

source:
  fn: libogg-1.3.2.tar.gz [win]
  url: http://www.rennert.io/dep_sources/libogg-1.3.2.tar.gz [win]
  fn: libogg-1.3.2.tar.gz [osx]
  url: http://www.rennert.io/dep_sources/libogg-1.3.2.tar.gz  [osx]
  #sha1: 37e04d73df8604df2581eeaf374aa3e521231694
	
build:
    number: 0
	  
requirements:
  build:

  run:
    - libogg

about:
  home: https://xiph.org/ogg/
  license: "BSD-STYLE SOURCE LICENSE"
  summary: "Ogg is a multimedia container format, and the native file and stream format for the Xiph.org multimedia codecs."
