package:
  name: videotagger
  version: 0.0.4


source:
  fn: pyTools-master.zip
  sha256: ae5b9d1bd6b0a61fe6115c804ef1f5ef956e0bc199ee27442338c094f235c5dd
  url: http://peter.rennert.io/exchange/pyTools/pyTools-master.zip
  
build:                   
  number: 0

requirements:
  build:
    - videotagger-dependencies
    - setuptools
    - python
    - distribute
	
  run:
    - videotagger-dependencies
    - setuptools
    - distribute


about:
  home: https://www.github.com/groakat/pyTools/
