package:
  name: videotagger
  version: 0.0.1


source:
  fn: pyTools-plugins.zip
  url: https://dl.dropboxusercontent.com/u/45267030/secretCode/pyTools-plugins.zip
  
build:                   
  number: 0

requirements:
  build:
    - videotagger-dependencies
    - setuptools
    - python
    - distribute
	
  run:
    - videotagger-dependencies
    - setuptools
    - distribute


about:
  home: https://www.github.com/groakat/pyTools/
