package:
  name: videotagger
  version: 0.0.7


source:
  fn: pyTools-master.zip
  sha256: ce6b0fa4a5a8ccbf33ac2cb27dbc77f0dac3009211ccd860b019a38d11c61d5f
  url: http://peter.rennert.io/exchange/pyTools/pyTools-master.zip
  
build:                   
  number: 2

requirements:
  build:
    - videotagger-dependencies
    - setuptools
    - python
    - distribute
    - cython             [win]
    - mingw				 [win]
    - pywin32           [win]
    - libpython         [win]
	
  run:
    - videotagger-dependencies
    - setuptools
    - distribute


about:
  home: https://www.github.com/groakat/pyTools/
