package:
  name: zerorpc
  version: 0.4.4

source:
  fn: zerorpc-0.4.4.tar.gz
  url: https://pypi.python.org/packages/source/z/zerorpc/zerorpc-0.4.4.tar.gz
  md5: cb54bfbc3c3068dab482e95c543c6e03

build:
    number: 0
  
requirements:
  build:
    - python
    - setuptools
    - gevent
    - greenlet
    - pyzmq ==13.1.0
    - msgpack-python

  run:
    - python
    - pyzmq ==13.1.0
    - gevent
    - msgpack-python

test:
  # Python imports
  imports:
    - zerorpc

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/dotcloud/zerorpc-python
  license: MIT License

