package:
  name: zerorpc
  version: 0.5.2

source:
  fn: zerorpc-python-master.zip
  url: https://github.com/0rpc/zerorpc-python/archive/master.zip
  sha256: 619e6ba846f5a98c26c93d8273da4c12b09a5c0f0467c9e379d92c820e71ecd2

build:
    number: 1
  
requirements:
  build:
    - python
    - setuptools
    - gevent
    - greenlet
    - pyzmq
    - msgpack-python

  run:
    - python
    - pyzmq
    - gevent
    - msgpack-python
    - setuptools

test:
  # Python imports
  imports:
    - zerorpc

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/dotcloud/zerorpc-python
  license: MIT License

