package:
  name: pyzmq
  version: 13.1.0

requirements:
  build:
    - python
    - pip

  run:
    - python

about:
  home: http://msgpack.org/
  license: ache Software License
  summary: MessagePack (de)serializer.
