package:
  name: pygp
  version: 1.3.2

source:
  fn: v1.3.2.tar.gz
  url: https://github.com/marionmari/pyGPs/archive/v1.3.2.tar.gz
  
build:                   
  number: 0          

requirements:
  build:
    - python
    - scipy
    - numpy
    - matplotlib
	
  run:
    - python
    - scipy
    - numpy
    - matplotlib


about:
  home: https://github.com/noxrepo/pox
  license: Apache 2.0
