package:
  name: pathos
  version: 0.2a1

source:
  git_url: https://github.com/uqfoundation/pathos.git
#  md5: cf42c695fab68116af2c8ef816fca0d9
  
build:                   
  number: 1          

requirements:
  build:
    - python
    - dill
    - pox
    - pyre
    - ppft
    - multiprocess
    - pyina
	
  run:
    - python
    - dill
    - pox
    - pyre
    - ppft
    - multiprocess
    - pyina


about:
  home: https://github.com/uqfoundation/pathos
  license: 3-clause BSD
