package:
  name: fdk-aac
  version: 0.1.4

source:
  fn: fdk-aac-0.1.4.tar.gz [win]
  url: http://www.rennert.io/dep_sources/fdk-aac-0.1.4.tar.gz [win]
  fn: fdk-aac-0.1.4.tar.gz [osx]
  url: http://www.rennert.io/dep_sources/fdk-aac-0.1.4.tar.gz  [osx]
  #sha1: 37e04d73df8604df2581eeaf374aa3e521231694
	
build:
    number: 0
	  
requirements:
  build:

  run:

about:
  home: http://sourceforge.net/projects/opencore-amr/files/fdk-aac/
  license: "Custom: Software License for The Fraunhofer FDK AAC Codec Library "
  summary: 'The Fraunhofer FDK AAC Codec Library for Android ("FDK AAC Codec") is software that implements the MPEG Advanced Audio Coding ("AAC") encoding and decoding scheme for digital audio'
